name: my-first pipeline file
on: [push]
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code to Server
        uses: actions/checkout@v4

      - name: List My Project Files
        run: ls -la
