name: my-first pipeline file
on: [push]
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code to Server
        uses: actions/checkout@v4

      - name: Audit Chaos Script
        uses: koalaman/shellcheck-action@v2
        with:
          path: ./chaos-monkey.sh
